gestionInstituto/urls.py
from django.contrib import admin
from django.urls import path, include
from inscripcionFinales import views

urlpatterns = [
    path('admin/', admin.site.urls, name='login'),
    path('', include("inscripcionFinales.urls")),
]

inscripcionFinales/urls.py
from re import template
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from .views import *


urlpatterns = [
    #Usuarios del sistema   
    path('', HomePageView.as_view(), name= 'inicio'),
    path('accounts/login/', CustomLoginView.as_view(), name='login'),
    path('accounts/logout/', CustomLogoutView.as_view(), name='logout'),
    path("accounts/", include("django.contrib.auth.urls")),
    path("recuperar_pass/",auth_views.PasswordResetView.as_view(template_name="registration/recuperar_pass.html"),name='Recuperar Contraseña'),
    path("password_reset_done/", auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_send.html"), name='password_reset_done'),
    path("create_user/",login_required(registerView.as_view(template_name= 'registration/register.html')), name='register'),
    path("career/", login_required(carreraView.as_view(template_name= 'carrera.html')), name='carrera'),
    path("institut/", login_required(carreraView.as_view(template_name= 'instituto.html')), name='instituto'),
    path("show_profile/", login_required(profileviews.as_view(template_name= 'registration/profile.html')), name='profile'),
    path("change_password/", auth_views.PasswordChangeView.as_view(template_name = 'registration/change_password.html'),name = 'cambiar_contraseña'),
    path("change_password_done/",auth_views.PasswordChangeDoneView.as_view(template_name='registration/success_password.html'), name='password_change_done'),
    path("user_list/",login_required(listUser.as_view(template_name='registration/list_user.html')),name='list_user'),
    path("edit_user/<int:pk>",login_required(editUser.as_view(template_name = 'registration/edit_profile.html')), name='edit_profile'),
    path("delete_user/<int:pk>",login_required(deleteUser.as_view(template_name='registration/delete_user.html')),name='delete_user'),
    path("show_user/<int:pk>",login_required(editUser.as_view(template_name = 'registration/show_user.html')), name='show_user'),
    #Alta e Inscripcion materias
    path('altaMateria/', alta_materia, name='altaMateria'),
    path('exito-alta-materia/', exito_alta_materia, name='exito_alta_materia'),
    path('lista_materias_admin/', lista_materias_admin, name='listaMateriasAdmin'),
    path('lista_materias_user/', lista_materias_user, name='listaMateriasUser'),
    path('inscribirse_materia/<int:materia_id>', inscribirse_materia, name='inscribirse_materia'),
    path('alta_masiva_materia/', alta_masiva_materia, name= 'AltaMasivaMaterias'),
    path('editar_materia/<int:id>/', editar_materia, name='editar_materia'),
    path('ver_materias/<int:id>/', ver_materias, name='ver_materias'),
    path('eliminar_materia/<int:id>/', eliminar_materia, name='eliminar_materia'),
    path('exito_materia_eliminada/', exito_materia_eliminada, name='exito_materia_eliminada'),
    path('lista_materias_admin/', lista_materias_admin, name='lista_materias_admin'),
    #Alta e Inscripcion mesa de final Administrativo
    path('mesas_finales/', MesasFinalesListView.as_view(), name='mesas_finales_list'),
    path('inscribir_mesa_final/', inscribir_mesa_final, name='inscribir_mesa_final'),
    #Alta e Inscripcion mesa de final
    path('altaMesa/',altaMesa, name='altaMesa'),
    path('inscripcionMesa/',inscripcionMesa,name='inscripcionMesa'), 
    path('exito-inscripcion/', exito_inscripcion_final, name='exito_inscripcion_final'),
    path('exito_alta_mesa/', exito_alta_mesa, name='exito_alta_mesa'),
    path('inscripcionFinal/',inscripcionFinal, name='inscripcionFinal'),
    path('inscripcionFinal_est/',inscripcionFinal_est, name='inscripcionFinal_est'),
    path('exito_inscripcion_mesa/', exito_inscripcion_mesa, name='exito_inscripcion_mesa'),
    path('error_alta_mesa/', error_alta_mesa, name='error_alta_mesa'),
    path('error_inscripcion_adm/', error_inscripcion_adm, name='error_inscripcion_adm'),
    path('error_inscripcion_est/', error_inscripcion_est, name='error_inscripcion_est'),
    path("inscripcion_finales_lista/",login_required(listInscripcion.as_view(template_name='finales/list_inscripcion.html')),name='list_inscripcion'),
    path("mesas_lista/",login_required(listMesa.as_view(template_name='finales/list_mesa.html')),name='list_mesa'),
    path("delete_mesa/<int:pk>",login_required(deleteMesa.as_view(template_name='finales/delete_mesa.html')),name='delete_mesa'),
    path("delete_inscripcion/<int:pk>",login_required(deleteInscripcion.as_view(template_name='finales/delete_inscripcion.html')),name='delete_inscripcion'),
    #Estudiantes
    path('estudiantes/nuevo', EstudianteCreateView.as_view(), name='estudiante_nuevo'),
    path('estudiantes/<int:pk>/editar/', EstudianteUpdateView.as_view(), name='estudiante_editar'),
    path('estudiantes/<int:pk>/eliminar/', EstudianteDeleteView.as_view(), name='estudiante_eliminar'),
    path('cargaMasivaEstudiantes/',cargar_usuarios,name='cargaMasivaEstudiantes'),
    path('ver_usuario_materia/',listar_usuarios_materia,name='verUsuarioMateria'),
    

]

inscripcionFinales/models.py
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager, Group, PermissionsMixin, AbstractUser, User,)
from django.db import models
from django.utils.timezone import now
from .choices import ESTADO_CIVIL_CHOICES,SEXO_CHOICES,MODALIDAD_CHOICES
import random
#from django.contrib.auth.forms import PasswordChangeForm


class UsuarioManager(BaseUserManager):
    
    def create_user(self ,email, password, **extra_fields):
        if not email:
            raise ValueError('Los usuarios deben tener una direccion de email')

        user =self.model(
          email= self.normalize_email(email),
          
        )
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    
        
    def create_superuser(self, email, password, **extra_fields):
        user = self.create_user(
          email = self.normalize_email(email),
          password = password,
        )
        user.is_superuser = True
        user.is_admin = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class Usuario(AbstractBaseUser,PermissionsMixin):
      
    email = models.EmailField('email', max_length=254, unique = True)
    username = models.CharField('username',unique = True,null = True, max_length=100, blank=False)
    nombres = models.CharField('nombres', max_length=200, null=True, blank=True)
    apellidos = models.CharField('apellidos', max_length=200, null=True, blank=True)
    fecha_nac = models.DateField('fecha_nac', null=True, blank=True)
    dni = models.IntegerField('dni',unique = True, null= True, blank=True)
    direccion = models.CharField('direccion', max_length=50, null=True, blank=True)
    localidad = models.CharField('localidad', max_length=50, null=True, blank=True)
    ciudad = models.CharField('ciudad', max_length=100, null=True, blank=True)
    nacionalidad = models.CharField('nacionalidad',max_length=50, null=True, blank=True)
    telefono_1 = models.IntegerField('telefono_1', null=True, blank=True)
    telefono_2 = models.IntegerField('telefono_2', null=True, blank=True)
    estado_civil=models.CharField('estado_civil', choices=ESTADO_CIVIL_CHOICES,max_length=50, null=True, blank=True)
    sexo=models.CharField('sexo',choices=SEXO_CHOICES,max_length=2, null=True, blank=True)
    imagen = models.ImageField('imagenPerfil', upload_to='perfil/', max_length=200, null=True, blank=True)
    is_admin = models.BooleanField('is_admin', default=False)
    is_superuser = models.BooleanField('is_superuser', default=False)
    is_active = models.BooleanField(default = True)
    is_staff = models.BooleanField(default = False)
    carrera = models.ManyToManyField('Carrera',blank=True)
    Estudiante = 'Estudiante'          
    Preceptor = 'Preceptor'
    Profesor = 'Profesor'
    Directivo = 'Directivo'
    Administrador = 'Administrador'
    

    ROL_CHOICES = (
        (Directivo, 'Directivo'),
        (Preceptor, 'Preceptor'),
        (Profesor, 'Profesor'),
        (Estudiante, 'Estudiante'),
        (Administrador, 'Administrador'),
        
     )
    rol = models.CharField(max_length=20, choices=ROL_CHOICES, default=Estudiante)
    objects = UsuarioManager()
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['password']

    
    def __str__(self):
        return self.email

    


class Carrera(models.Model):
    nombre_carrera = models.CharField('nombre_carrera',unique = True, max_length=100)
    num_resolucion = models.CharField('num_resolucion', max_length=100, blank = True, null = True)
    duracion_carrera = models.PositiveBigIntegerField(default=3)
    instituto = models.ForeignKey('Instituto',on_delete=models.CASCADE,null=True)
    
    def __str__(self):
        return self.nombre_carrera
    
    

class usuarios_carreras(models.Model):
    carreras = models.ManyToManyField('Carrera', blank=False)
    usuario= models.ManyToManyField('Usuario', blank=False)
    
class materia_carrera(models.Model):
    materia = models.ForeignKey('Materia', on_delete=models.CASCADE, null=True)
    carrera = models.ForeignKey('Carrera', on_delete=models.CASCADE, null=True)

class Instituto(models.Model):
    nombre_instituto = models.CharField('nombre_instituto',unique = True, max_length=100)
    email_instituto = models.EmailField('email_instituto', max_length=254, unique = True)
    direccion=models.CharField('direccion', max_length=50)
    localidad=models.CharField('localidad', max_length=50)
    ciudad=models.CharField('ciudad', max_length=100)
    telefono_1 = models.IntegerField('telefono_1')
    telefono_2 = models.IntegerField('telefono_2')
    
    imagen = models.ImageField('imagenPerfil', upload_to='perfil/', max_length=200,blank = True,null = True)
    
    def __str__(self):
        return self.nombre_instituto


class Materia(models.Model):
    nombre_materia = models.CharField('nombre_materia',unique = True, max_length=30)
    carrera = models.ForeignKey('Carrera',on_delete=models.CASCADE,null=True)
    profesor = models.ForeignKey('Usuario',on_delete=models.CASCADE,null=True)

    Inicio = '12:00'
    Inicio1 = '14:00'
    Inicio2 = '16:00'
    Inicio3 = '18:00'
    Inicio4 = '20:00'
    
    HORARIO_CHOICES = ( 
        (Inicio, '12:00'),
        (Inicio1, '14:00'),
        (Inicio2, '16:00'),
        (Inicio3, '18:00'),
        (Inicio4, '20:00')
        )
    Horario=models.CharField(max_length=22, choices=HORARIO_CHOICES, default=Inicio)   
   
    
    Primero=1
    Segundo=2
    Tercero=3
    ANIO_CHOICES = (
        (Primero, 1),
        (Segundo, 2),
        (Tercero, 3),        
     )
    anio=models.IntegerField(choices=ANIO_CHOICES, default=Primero)
    
    def __str__(self):
        return self.nombre_materia
    


class MateriaCorrelativa(models.Model):
    materia = models.ForeignKey(Materia, on_delete=models.CASCADE, related_name='materias_correlativas')
    materia_correlativa = models.ForeignKey(Materia, on_delete=models.CASCADE, related_name='correlativas_de')

    def __str__(self):
        return f"{self.materia} -> {self.materia_correlativa}"

class usuarios_materia(models.Model):
    materia = models.ForeignKey('Materia',on_delete=models.CASCADE,null=False, blank=False)
    usuario= models.ForeignKey('Usuario',on_delete=models.CASCADE,null=False, blank=False)
    nota_cursada=models.FloatField('Nota de Cursada',null=True,blank=True)
    nota_final=models.FloatField('Nota de Final',null=True,blank=True)
    aprobada= models.BooleanField(default=False)
    modalidad=models.CharField('Modalidad',choices=MODALIDAD_CHOICES,max_length=2, null=True, blank=True)
    ciclo_lectivo=models.CharField('Ciclo lectivo',unique = True,null=True, blank=True, max_length=100)

    def __str__(self):
        return f"{self.materia} -> {self.usuario}"
    
    def puede_inscribirse_en_mesa_final(self):
        return (self.nota_cursada >= 4 or self.modalidad == 'Libre') and self.aprobada == False
    
class MesaFinal(models.Model):
    materia= models.ForeignKey(Materia, on_delete=models.CASCADE, blank=False, null=False )
    llamado= models.DateTimeField('Llamado', null=False, blank=False) 
    vigente= models.BooleanField(default=True) 
    def __str__(self):
        return f"{self.materia} -> {self.llamado}"

class InscripcionFinal(models.Model):
    usuario= models.ForeignKey(Usuario, on_delete=models.CASCADE, blank=False, null=False)
    llamado= models.ForeignKey(MesaFinal, on_delete=models.CASCADE, blank=False, null=False)
    aprobada= models.BooleanField(null=True) 


class Estudiante(Usuario):
    matricula= models.CharField(max_length=10,unique=True)

class Profesor(Usuario):
    especialidad = models.CharField(max_length=100)

class Directivo(Usuario):
    cargo = models.CharField(max_length=100)

class Preceptor(Usuario):
    area = models.CharField(max_length=100)

inscripcionFinales/templates/materias/alta_masiva_materia.html
{% extends 'base/base.html' %}
{% block title %}Alta de Materia{% endblock %}
{% block content %}

    <div class="container">
        <h2>Importar Materias</h2>
        <form method="post"enctype="multipart/form-data">
            {% csrf_token %}
            <strong>{{ form.as_p }}</strong>
            <div>
                <br> <button type="submit" class="btn btn-primary">Carga Masiva</button> <br>
            </div>
    </div>
{% endblock %}

inscripcionFinales/templates/materias/alta_materia.html
{% extends 'base/base.html' %}
{% block title %}Alta de Materia{% endblock %}
{% block content %}
{% load static %}
    <div id="crear-materia"> 
        <form method="POST" class="form">
            <div class="edit-rectangulo1">
                {% csrf_token %}
                <p class = "text-center reg-titles">
                    Completar los siguientes campos:
                <br>
                </p>
                <p class="text-left form-items">
                    <label for="id_nombreDeMateria">Nombre de materia:</label>
                    {{ form.nombre_materia }}
                </p>
                <p class="text-left form-items">
                    <label for="id_carrera">Carrera:</label>
                    {{ form.carrera }}
                </p>
                <p class="text-left form-items">
                    <label for="id_profesor">Profesor:</label>
                    {{ form.profesor }}
                </p>
                <p class="form-left-horario form-items">
                    <label for="id_Año">Año:</label>
                    {{ form.anio }}
                <p>
                <p class="form-left-horario form-items">
                    <label for="id_horario">Horario:</label>
                    {{ form.Horario}}
                </p>
                <br>
            </div>
        <div class="cp-rectangulo2">
            <div class="logo-registracion only-lt">
                <img src="/static/imagenes/Logo_i210_fondo_trans.png" class="logo-reg only-lt">
            </div>
            <div class="botones-edituser">
                <button type="submit" class="btn btn-blue" >Guardar</button>
            </div>
        </div>
    </div>
{% endblock %}

inscripcionFinales/templates/materias/editar_materia.html
<!-- editar_materia.html -->
{% extends 'base/base.html' %}
{% block title %}Editar Materia{% endblock %}
{% block content %}
{% load static %}
    <div id="crear-materia"> 
        <form method="POST" class="form">
            <div class="edit-rectangulo1">
                {% csrf_token %}
                <p class = "text-center reg-title">
                    Editar Materia
                <br>
                </p>
                <p class="text-left form-items">
                    <label for="id_nombreDeMateria">Nombre de materia:</label>
                    <br>  
                    {{ form.nombre_materia }}
                </p>
                <p class="text-left form-items">
                    <label for="id_carrera">Carrera:</label>
                    <br>  
                    {{ form.carrera }}
                </p>
                <p class="text-left form-items">
                    <label for="id_profesor">Profesor:</label>
                    <br>  
                    {{ form.profesor }}
                </p>
                <p class="form-left-horario form-items">
                    <label for="id_Año">Año:</label>
                    {{ form.anio }}
                </p>
                <p class="form-left-horario form-items">
                    <label for="id_horario">Horario:</label>
                    {{ form.Horario}}
                </p><br>
            </div>
        <div class="cp-rectangulo2">
            <div class="logo-registracion only-lt">
                <img src="/static/imagenes/Logo_i210_fondo_trans.png" class="logo-reg only-lt">
            </div>
            <div class="botones-edituser">
                <button type="submit" class="btn btn-blue" >Guardar</button>
            </div>
        </div>
    </div>
{% endblock %}

inscripcionFinales/templates/materias/eliminar_materia.html
{% extends 'base/base.html' %}

{% block title %}Eliminar Materia{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">Eliminar Materia</h4>
        </div>
        <div class="card-body">
            <h6>¿Estás seguro de que quieres eliminar la materia "<b>{{ materia.nombre_materia }}</b>"?</h6>
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Eliminar</button>
                <a href="{% url 'lista_materias_admin' %}" class="btn btn-primary">Cancelar</a>
            </form>
        </div>
    </div>
{% endblock %}

inscripcionFinales/templates/materias/exito_alta_materia.html
{% extends 'base/base.html' %}

{% block title %}Alta de Materia Exitosa{% endblock %}

{% block content %}

<div>        
        <!-- Modal -->
        <div class="modal fade" id="alertModal" tabindex="-1" aria-labelledby="alertModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="alertModalLabel">Notificación</h5>
                    </div>
                    <div class="modal-body">
                        <h6>¡La materia ha sido creada correctamente!
                    </div>
                    <div class="modal-footer">
                        <a href="/lista_materias_admin/"><button type="button" class="btn btn-primary">Volver</button></a>
                    </div>
                </div>
            </div>
        </div>
    
        <!-- Scripts Bootstrap -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    
        <!-- Mostrar modal usando JavaScript -->
        <script>
            $(document).ready(function() {
                $('#alertModal').modal('show');
            });
        </script>
    
</div>
    

{% endblock %}

inscripcionFinales/templates/materias/exito_materia_eliminada.html
{% extends 'base/base.html' %}

{% block title %}Exito borrado materia{% endblock %}

{% block content %}

<div>        
        <!-- Modal -->
        <div class="modal fade" id="alertModal" tabindex="-1" aria-labelledby="alertModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="alertModalLabel">Notificación</h5>
                    </div>
                    <div class="text-center">
                        <h5>¡La materia ha sido eliminada correctamente!</h5>
                    </div>
                    <div class="modal-footer">
                        <a href="/lista_materias_admin/"><button type="button" class="btn btn-primary">Volver</button></a>
                    </div>
                </div>
            </div>
        </div>
    
        <!-- Scripts Bootstrap -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    
        <!-- Mostrar modal usando JavaScript -->
        <script>
            $(document).ready(function() {
                $('#alertModal').modal('show');
            });
        </script>
    
</div>
    

{% endblock %}

inscripcionFinales/templates/materias/lista_materias_admin.html
<!-- lista_materias_user.html -->
{% extends 'base/base.html' %}

{% block title %}Lista de Materias{% endblock %}


{% block content %}

    <div class="card">
        <div class="card-headers">
            <h3 class="card-title">Listado de Materias</h3>
        </div>

        <div class="card-body">
            <table class="table table-striped table-bordered">
                {% load static %}
                    <tr>
                        <th class="h5">ID</th>
                        <th class="h5">Nombre</th>
                        <th class="h5">Año</th>
                        <th class="h5">Carrera</th>
                        <th class="h5">Profesor</th>
                        <th class="h5">Horario</th>
                        <th class="h5">Acciones</th>
                    </tr>
                <tbody>
                    {% if materias %}
                        {% for materia in materias %}
                            <tr>
                                <td class="h6">{{materia.id}}</td>
                                <td class="h6">{{materia.nombre_materia}}</td>
                                <td class="h6">{{materia.anio}}</td>
                                <td class="h6">{{materia.carrera.nombre_carrera}}</td>
                                <td class="h6">{{materia.profesor.nombres}}</td>
                                <td class="h6">{{materia.Horario}}</td>

                                <td>
                                    <a class="btn btn-primary" href="{% url 'ver_materias' id=materia.id %}" role="button">Ver</a>
                                    <a class="btn btn-primary" href="{% url 'editar_materia' id=materia.id %}" role="button">Editar</a>
                                    <a class="btn btn-danger" href="{% url 'eliminar_materia' id=materia.id %}" role="button">Eliminar</a>

                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger"> No hay materias disponibles.</div>
                    {% endif %}
                </tbody>
            </table>
          
        </div>
    </div>
   

{% endblock %}

inscripcionFinales/templates/materias/lista_materias_user.html
<!-- lista_materias_user.html -->
{% extends 'base/base.html' %}

{% block title %}Lista de Materias{% endblock %}

{% block content %}

    <div class="card">
        <div class="card-header">
        </div>
        <div class="card-body">
            <h4 class="card-title">Lista de Materias</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th class="h5">ID</th>
                        <th class="h5">Nombre</th>
                        <th class="h5">Año</th>
                        <th class="h5">Carrera</th>
                        <th class="h5">Profesor</th>
                        <th class="h5">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% if materias %}
                        {% for materia in materias %}
                            <tr>
                                <td class="h6">{{materia.id}}</td>
                                <td class="h6">{{materia.nombre_materia}}</td>
                                <td class="h6">{{materia.anio}}</td>
                                <td class="h6">{{materia.carrera.nombre_carrera}}</td>
                                <td class="h6">{{materia.profesor.nombres}}</td>
                                <td>
                                    <a name="" id="" class="btn btn-primary" href="#" role="button">Inscribirme</a>
                                    <a name="" id="" class="btn btn-primary" href="#" role="button">Ver detalles</a>
                                    <a name="" id="" class="btn btn-danger" href="#" role="button">Dar de baja</a>
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger"> No hay materias disponibles.</div>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

inscripcionFinales/templates/materias/ver_materia.html
{% extends 'base/base.html' %}

{% block title %}Ver materia{% endblock %}

{% block content %}
<h1 style="margin-top: -50px">{{ materia.nombre_materia }}</h1>
<div style="margin-top: -170px">
  {% comment %} <form method="post" class="">
    {% csrf_token %} {% endcomment %}
    <div class="card p-3 mb-2 bg-light">
      <div class="card-body p-3 mb-2">
<div class="position-absolute top-50 start-50 translate-middle"></div>
    <p class="h6 fw-semibold">
      Nombre de la materia: {{ materia.nombre_materia }}
    </p>
    <p class="h6 fw-semibold">
      Carrera: {{materia.carrera.nombre_carrera}}
    </p>
    <p class="h6 fw-semibold">
      Profesor: {{materia.profesor.nombres }}
    </p>
    <p class="h6 fw-semibold">
      Año: {{ materia.anio }}
    </p>
    <p class="h6 fw-semibold">
      Horario: {{ materia.Horario }}
    </p>
</div>

<p>
  
  <a href="/lista_materias_admin/"><button type="button" class="btn btn-primary">Volver</button></a>
  <a href="{% url 'editar_materia' id=materia.id %}">
    <button type="button" class="btn btn-primary" style="margin-left: 160px">Editar</button>
  </a>
{% endblock %}